# Generated by Django 4.0 on 2022-01-08 11:51

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.TimeField(default=main.models.default_start_time),
        ),
    ]
