# Generated by Django 4.0 on 2022-02-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_date_news_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
