# Generated by Django 4.0.4 on 2022-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutschool_alter_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutschool',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
