# Generated by Django 4.0.4 on 2022-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutschool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutschool',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Порядковый номер'),
        ),
    ]
