# Generated by Django 4.0.4 on 2022-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_widgetlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetlinks',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='widgetlinks',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок'),
        ),
    ]
