# Generated by Django 4.0.4 on 2022-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_widgetlinks_link_alter_widgetlinks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetlinks',
            name='id',
        ),
        migrations.AlterField(
            model_name='widgetlinks',
            name='title',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='Заголовок'),
        ),
    ]
