# Generated by Django 4.0.4 on 2022-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_widgetlinks_id_alter_widgetlinks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetlinks',
            name='gradient',
            field=models.CharField(choices=[('blue-white', 'Синий-белый'), ('red-white', 'Красный-белый'), ('green-white', 'Зелёный-белый'), ('purple-orange', 'Фиолетовый-бежевый')], default='blue-white', max_length=20, verbose_name='Градиент'),
        ),
    ]
