# Generated by Django 4.0.4 on 2022-09-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_widgetlinks_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetlinks',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widgetlinks',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок'),
        ),
    ]
